sf:
  clientSecret: "![Vao+eyl+8KnS0Jrut/Y0ObzE1OJyhB9jztfKsQkMvWr2F+wbreYHilmVKHmepj12Ox9UhIKk4/h9gVnWxp9imHBO2KyFmCY6D8qDxXJndJo=]"
  
associateService:
  clientSecret: "![7qWB80U2r7QxkHzRwS6erEAy0jf7T5yjWt+TyjPqSwVjvuftjArEejkiwBV+FPrF]"

graphAPI:
  clientSecret: "![4T4Cev+p4IDtU3KbLkpDc1o1Iv3Wd2Ruj0M/CPm9+AUVgF/oidLbj4vg2zapPgsc]"
  