sf:
  clientSecret: "![eilWs1io/ZcYB6dGPUTgJrWQPTx61QeN8p6ZD1xZ3eWSTZOKzuTXqPnOyMLgTV6z26uQkqPLzBhBvVP2tASyfDlyTSVUbSjwGIfkJilieLA=]"  

associateService:
  clientSecret: "![jOt14lhOAmCTDyIi94zPZ3dLLsJl4LkcGMGKxNwq34n7uYHapSVKt6vJYkQbM+YZ]"
    
graphAPI:
  clientSecret: "![kJpxrp4ZCCyCaVEPYzswkE2fHlefiZ755UZPyCcSQgqjv54MSMW21B+QceJDlhWo]"
  